// This file was generated by dtk-settings-tools version 0.1.2

#include <DSettings>

void GenerateSettingTranslate() {
    auto basic_interface_blurred_backgroundText = QObject::tr("Blur background");
    auto basic_interface_colorSchemeName = QObject::tr("Theme");
    auto basic_interface_fontFamilyName = QObject::tr("Font family");
    auto basic_interface_fontSizeName = QObject::tr("Font size");
    auto basic_interface_opacityName = QObject::tr("Opacity");
    auto basic_cursor_cursorBlinkText = QObject::tr("Cursor blink");
    auto basic_cursor_cursorShapeName = QObject::tr("Cursor shape");
    auto basic_layout_verticalTabsText = QObject::tr("Vertical Tabs");
    auto advanced_session_sessionRestoreText = QObject::tr("Save and restore session");
    auto advanced_session_sessionRestoreBehaviorName = QObject::tr("Restore behavior");
    auto advanced_scrolling_scrollbackLinesName = QObject::tr("Scrollback lines");
    auto group_basicName = QObject::tr("Basic");
    auto group_advancedName = QObject::tr("Advanced");
    auto group_advanced_scrollingName = QObject::tr("Scrolling");
    auto group_advanced_sessionName = QObject::tr("Session Management");
    auto group_basic_cursorName = QObject::tr("Cursor");
    auto group_basic_interfaceName = QObject::tr("Interface");
    auto group_basic_layoutName = QObject::tr("Layout");
    auto group_shortcutsName = QObject::tr("Shortcuts");
    auto group_shortcuts_advancedName = QObject::tr("Advanced");
    auto group_shortcuts_tabName = QObject::tr("Tabs");
    auto group_shortcuts_terminalName = QObject::tr("Terminal");
    auto shortcuts_advanced_custom_commandName = QObject::tr("Custom commands");
    auto shortcuts_advanced_display_shortcutsName = QObject::tr("Display shortcuts");
    auto shortcuts_advanced_remote_managementName = QObject::tr("Remote management");
    auto shortcuts_advanced_restore_sessionName = QObject::tr("Restore previous session");
    auto shortcuts_advanced_rename_titleName = QObject::tr("Rename title");
    auto shortcuts_advanced_switch_fullscreenName = QObject::tr("Fullscreen");
    auto shortcuts_tab_close_other_tabsName = QObject::tr("Close other tabs");
    auto shortcuts_tab_close_other_workspacesName = QObject::tr("Close other workspaces");
    auto shortcuts_tab_close_tabName = QObject::tr("Close tab");
    auto shortcuts_tab_close_workspaceName = QObject::tr("Close workspace");
    auto shortcuts_tab_horionzal_splitName = QObject::tr("Horizontal split");
    auto shortcuts_tab_new_tabName = QObject::tr("New tab");
    auto shortcuts_tab_next_tabName = QObject::tr("Next tab");
    auto shortcuts_tab_previous_tabName = QObject::tr("Previous tab");
    auto shortcuts_tab_select_left_workspaceName = QObject::tr("Select left workspace");
    auto shortcuts_tab_select_lower_workspaceName = QObject::tr("Select lower workspace");
    auto shortcuts_tab_select_right_workspaceName = QObject::tr("Select right workspace");
    auto shortcuts_tab_select_upper_workspaceName = QObject::tr("Select upper workspace");
    auto shortcuts_tab_switch_label_win_1Name = QObject::tr("Go to tab 1");
    auto shortcuts_tab_switch_label_win_2Name = QObject::tr("Go to tab 2");
    auto shortcuts_tab_switch_label_win_3Name = QObject::tr("Go to tab 3");
    auto shortcuts_tab_switch_label_win_4Name = QObject::tr("Go to tab 4");
    auto shortcuts_tab_switch_label_win_5Name = QObject::tr("Go to tab 5");
    auto shortcuts_tab_switch_label_win_6Name = QObject::tr("Go to tab 6");
    auto shortcuts_tab_switch_label_win_7Name = QObject::tr("Go to tab 7");
    auto shortcuts_tab_switch_label_win_8Name = QObject::tr("Go to tab 8");
    auto shortcuts_tab_switch_label_win_9Name = QObject::tr("Go to tab 9");
    auto shortcuts_tab_vertical_splitName = QObject::tr("Vertical split");
    auto shortcuts_terminal_copyName = QObject::tr("Copy");
    auto shortcuts_terminal_default_sizeName = QObject::tr("Default size");
    auto shortcuts_terminal_findName = QObject::tr("Find");
    auto shortcuts_terminal_pasteName = QObject::tr("Paste");
    auto shortcuts_terminal_select_allName = QObject::tr("Select all");
    auto shortcuts_terminal_zoom_inName = QObject::tr("Zoom in");
    auto shortcuts_terminal_zoom_outName = QObject::tr("Zoom out");
}
